//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISFMOCM_DBEntities : DbContext
    {
        public ISFMOCM_DBEntities()
            : base("name=ISFMOCM_DBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_AccountChapter> tbl_AccountChapter { get; set; }
        public virtual DbSet<tbl_AccountType> tbl_AccountType { get; set; }
        public virtual DbSet<tbl_Expense> tbl_Expense { get; set; }
        public virtual DbSet<tbl_ExpenseDetail> tbl_ExpenseDetail { get; set; }
        public virtual DbSet<tbl_FCV> tbl_FCV { get; set; }
        public virtual DbSet<tbl_InitialBudget> tbl_InitialBudget { get; set; }
        public virtual DbSet<tbl_InitialPettyCash> tbl_InitialPettyCash { get; set; }
        public virtual DbSet<tbl_InitialPettyCashDetail> tbl_InitialPettyCashDetail { get; set; }
        public virtual DbSet<tbl_Mandate> tbl_Mandate { get; set; }
        public virtual DbSet<tbl_MandateDetail> tbl_MandateDetail { get; set; }
        public virtual DbSet<tbl_Responsible_Unit> tbl_Responsible_Unit { get; set; }
        public virtual DbSet<tbl_Transfer> tbl_Transfer { get; set; }
        public virtual DbSet<tbl_TransferDetail> tbl_TransferDetail { get; set; }
        public virtual DbSet<tbl_Unit> tbl_Unit { get; set; }
        public virtual DbSet<tbl_year> tbl_year { get; set; }
    }
}
