//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InitialPettyCashDetail
    {
        public int InitialPettyCashDetail_id { get; set; }
        public int InitialPettyCash_id { get; set; }
        public string Acc_no { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<System.DateTime> InitialPettyCash_date { get; set; }
    
        public virtual tbl_InitialPettyCash tbl_InitialPettyCash { get; set; }
    }
}
