//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransferDetail
    {
        public int TransferDetail_id { get; set; }
        public string Transfer_no { get; set; }
        public string Acc_no { get; set; }
        public Nullable<decimal> Transfer_increase { get; set; }
        public Nullable<decimal> Transfer_decrease { get; set; }
        public Nullable<decimal> Transfer_add { get; set; }
        public Nullable<int> Unit_id { get; set; }
        public Nullable<int> Transfer_id { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Transfer tbl_Transfer { get; set; }
    }
}
