//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mandate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Mandate()
        {
            this.tbl_MandateDetail = new HashSet<tbl_MandateDetail>();
        }
    
        public int Mandate_id { get; set; }
        public string Mandate_no { get; set; }
        public int Unit_id { get; set; }
        public Nullable<System.DateTime> Mandate_date { get; set; }
        public string Mandate_desc { get; set; }
        public string Reciever { get; set; }
        public string BankAcc_no { get; set; }
        public string BankAcc_address { get; set; }
        public string AmountInWord { get; set; }
        public string USD { get; set; }
        public Nullable<System.DateTime> MEF_date { get; set; }
        public Nullable<bool> Salary { get; set; }
        public Nullable<bool> Electricity { get; set; }
        public Nullable<bool> Water { get; set; }
        public Nullable<bool> Contribution { get; set; }
        public Nullable<bool> PettyCash { get; set; }
        public Nullable<bool> Advance { get; set; }
        public string AdvanceNumber { get; set; }
        public Nullable<System.DateTime> Advance_date { get; set; }
        public Nullable<bool> Allowance { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<bool> Telecom { get; set; }
        public string CurrencyType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MandateDetail> tbl_MandateDetail { get; set; }
    }
}
