//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Expense()
        {
            this.tbl_ExpenseDetail = new HashSet<tbl_ExpenseDetail>();
        }
    
        public int expense_id { get; set; }
        public Nullable<System.DateTime> expense_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ExpenseDetail> tbl_ExpenseDetail { get; set; }
    }
}
