//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InitialPettyCash
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_InitialPettyCash()
        {
            this.tbl_InitialPettyCashDetail = new HashSet<tbl_InitialPettyCashDetail>();
        }
    
        public int InitialPettyCash_id { get; set; }
        public int Unit_id { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual tbl_Unit tbl_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InitialPettyCashDetail> tbl_InitialPettyCashDetail { get; set; }
    }
}
