//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MandateDetail
    {
        public int MandateDetail_id { get; set; }
        public Nullable<int> Mandate_id { get; set; }
        public string Acc_no { get; set; }
        public Nullable<decimal> Mandate_amount { get; set; }
        public string FCV_no { get; set; }
        public Nullable<int> FCV_id { get; set; }
        public Nullable<int> FCV_Identity { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Mandate tbl_Mandate { get; set; }
    }
}
