//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InitialBudget
    {
        public int InitialBudget_id { get; set; }
        public string Acc_no { get; set; }
        public Nullable<System.DateTime> InitialBudget_date { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> Unit_id { get; set; }
        public Nullable<decimal> Direct_Paid { get; set; }
        public Nullable<decimal> PettyCash { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
    }
}
