//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FCV
    {
        public int FCV_id { get; set; }
        public string FCV_no { get; set; }
        public string Acc_no { get; set; }
        public Nullable<System.DateTime> FCV_date { get; set; }
        public Nullable<decimal> FCV_amount { get; set; }
        public string Letter_no { get; set; }
        public Nullable<System.DateTime> Letter_date { get; set; }
        public Nullable<System.DateTime> MEF_date { get; set; }
        public Nullable<decimal> MEF_amount { get; set; }
        public Nullable<decimal> AmountAfterProcurement { get; set; }
        public string Commitment_desc { get; set; }
        public string Dep_of_commitment { get; set; }
        public string Documentation { get; set; }
        public string AmountInLetter { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<bool> PettyCash { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<bool> Salary { get; set; }
        public Nullable<bool> Electricity { get; set; }
        public Nullable<bool> Water { get; set; }
        public Nullable<bool> Contribution { get; set; }
        public Nullable<bool> Advance { get; set; }
        public Nullable<bool> Allowance { get; set; }
        public Nullable<int> FCV_Identity { get; set; }
        public Nullable<bool> Telecom { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
    }
}
