//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Account()
        {
            this.tbl_ExpenseDetail = new HashSet<tbl_ExpenseDetail>();
            this.tbl_FCV = new HashSet<tbl_FCV>();
            this.tbl_InitialBudget = new HashSet<tbl_InitialBudget>();
            this.tbl_MandateDetail = new HashSet<tbl_MandateDetail>();
            this.tbl_TransferDetail = new HashSet<tbl_TransferDetail>();
            this.tbl_Unit = new HashSet<tbl_Unit>();
        }
    
        public int Acc_id { get; set; }
        public string Acc_no { get; set; }
        public int AccChapter_id { get; set; }
        public string Acc_code { get; set; }
        public string Acc_name { get; set; }
        public string Acc_desc { get; set; }
        public Nullable<int> Responsible_Unit_Id { get; set; }
        public string Geography { get; set; }
        public string Foundation { get; set; }
        public string SubAccount_Cluster { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tbl_AccountChapter tbl_AccountChapter { get; set; }
        public virtual tbl_Responsible_Unit tbl_Responsible_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ExpenseDetail> tbl_ExpenseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FCV> tbl_FCV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InitialBudget> tbl_InitialBudget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MandateDetail> tbl_MandateDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TransferDetail> tbl_TransferDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Unit> tbl_Unit { get; set; }
    }
}
