//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Transfer()
        {
            this.tbl_TransferDetail = new HashSet<tbl_TransferDetail>();
        }
    
        public int Transfer_id { get; set; }
        public string Transfer_no { get; set; }
        public Nullable<System.DateTime> Transfer_date { get; set; }
        public string Transfer_desc { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TransferDetail> tbl_TransferDetail { get; set; }
    }
}
