//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountChapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AccountChapter()
        {
            this.tbl_Account = new HashSet<tbl_Account>();
        }
    
        public int AccChapter_id { get; set; }
        public int AccType_id { get; set; }
        public string AccChapter_code { get; set; }
        public string AccChapter_name { get; set; }
        public Nullable<int> AccChapter_order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Account> tbl_Account { get; set; }
        public virtual tbl_AccountType tbl_AccountType { get; set; }
    }
}
