//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFMOCM_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Unit()
        {
            this.tbl_InitialPettyCash = new HashSet<tbl_InitialPettyCash>();
        }
    
        public int Unit_id { get; set; }
        public string Unit_name { get; set; }
        public string Unit_desc { get; set; }
        public Nullable<bool> status { get; set; }
        public string Acc_no { get; set; }
        public Nullable<int> Order_Number { get; set; }
        public Nullable<int> Unit_code { get; set; }
        public string unit_number { get; set; }
        public Nullable<int> Responsible_Unit_Id { get; set; }
        public string Geography { get; set; }
        public string Foundation { get; set; }
        public string SubAccount_Cluster { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InitialPettyCash> tbl_InitialPettyCash { get; set; }
        public virtual tbl_Responsible_Unit tbl_Responsible_Unit { get; set; }
    }
}
